lsコマンドを作る4
muftahpangestu/ruby-practices pull request #11
Opened 2023-09-13 08:39 UTC by muftahpangestu

2023-09-16 04:50 UTC, u1tnk requested changes

2023-09-16 04:50 UTC, u1tnk commented on 04.ls/command.rb
> +  max_length = 0
longがメソッドなので通常パターンもメソッドでまとめると読みやすいですね。

2023-09-16 04:50 UTC, u1tnk commented on 04.ls/command.rb
> +  file_list_long_mode = []
配列を用意してeachで入れるパターンはmapで置き替えられます。
頻出なので覚えておきましょう。

2023-09-16 04:50 UTC, u1tnk commented on 04.ls/command.rb
> +def long_list(file_list)
file_listは何を指しているかにもよりますが、rubyの慣習として配列は複数形なので単純にfileの配列であれば filesの方が適しています。

2023-09-16 04:50 UTC, u1tnk commented on 04.ls/command.rb
> +  column_max_lengths = column_spacing(file_list_long_mode)
max_lengthを計算するメソッドが spacingなのはちょっとわかりづらいので同じ名前にした方が良いと思います。

2023-09-19 05:38 UTC, muftahpangestu commented on 04.ls/command.rb
> +  max_length = 0
メソッド名変えました

2023-09-19 05:39 UTC, muftahpangestu commented on 04.ls/command.rb
> +def long_list(file_list)
変数の名変えました

2023-09-19 05:39 UTC, muftahpangestu commented on 04.ls/command.rb
> +  column_max_lengths = column_spacing(file_list_long_mode)
メソッド名変えました

2023-09-19 05:40 UTC, muftahpangestu commented on 04.ls/command.rb
> +  file_list_long_mode = []
mapメソッドはご存知ですが、こちらのコードにはそのメソッドを使えるケースを見つからないです、、

2023-09-19 16:42 UTC, u1tnk approved these changes

2023-09-20 01:17 UTC, merged