exercise four initial push
muftahpangestu/ruby-practices pull request #8
Opened 2023-08-18 01:57 UTC by muftahpangestu

2023-08-22 13:30 UTC, u1tnk requested changes

2023-08-22 13:30 UTC, u1tnk commented on 04.ls/command.rb
> +0.upto(file_list.length - 1) do |index|
indexが欲しいから uptoを使ったんでしょうか？
eachしつつ indexも貰える方法があるので調べてみてください。

2023-08-22 13:30 UTC, u1tnk commented on 04.ls/command.rb
> +  40 - filename.length
40だけだと意図が分かりづらいので、どういう意味なのかを考えて定数を使って定義するようにしましょう。

2023-08-22 13:30 UTC, u1tnk commented on 04.ls/command.rb
> +  print(current_file + ' ' * empty_space_length(current_file))
等幅にファイル名を表示するための処理だと思うのですが、 Stringクラスにもっと簡単にやりたい事を実現するメソッドがあるので調べてみてください。

2023-08-22 13:30 UTC, u1tnk commented on 04.ls/command.rb
> +0.upto(file_list.length - 1) do |index|
https://bootcamp.fjord.jp/pages/ls-command#requirements

以下の部分対応してますでしょうか？

```
 # ファイルの並び順は必ず以下のように並ぶようにしてください
# ※並び順の単純な位置関係を数値であらわしています。
#   実際のファイル名では文字列としての並び順でOKです。
#   (ファイル名が1と2と10なら1, 10, 2となっていてよい)
1 5 9
2 6 10
3 7
4 8

# この並び順はNGです
1  2  3
4  5  6
7  8  9
10 11
'''

2023-08-23 07:01 UTC, muftahpangestu commented on 04.ls/command.rb
> +0.upto(file_list.length - 1) do |index|
お求めファイル並びを対応できるため、ロジック変えました。新しロジックではファイルひとつひとつループしないですので`each`を使わず、`index`のままにしました。

2023-08-23 07:01 UTC, muftahpangestu commented on 04.ls/command.rb
> +  40 - filename.length
marginの変数に入れました。

2023-08-23 07:02 UTC, muftahpangestu commented on 04.ls/command.rb
> +  print(current_file + ' ' * empty_space_length(current_file))
ljustメソッド使いました

2023-08-23 14:57 UTC, u1tnk requested changes

2023-08-23 14:57 UTC, u1tnk commented on 04.ls/command.rb
> +0.upto(row_count - 1) do |index|
ちょっとまだ複雑すぎますね。

このロジックのままでも事前に file_listを整理しておくと良いと思います。
basenameを先にやっておくとか ループ内でやっている分岐を不要にするようにできると良いですね。

2023-08-28 02:14 UTC, muftahpangestu commented on 04.ls/command.rb
> +0.upto(row_count - 1) do |index|
ロジック変えました。ご確認お願いします

2023-08-28 15:13 UTC, u1tnk requested changes

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +COLUMN_SPACING = max_length
ここでCOLUMN_SPACINGを入れていてadd_spacing で使っていることは、この規模ならすぐに分かりますが、規模が増えてくるととても読みづらいです。
必要な値は引数などで渡すようにして、メソッド内で情報の出所がわかるようにしましょう。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +ROW_COUNT = (file_count / 3.to_f).ceil
ここも定数ではなく変数に入れましょう。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +CURRENT_PATH = ARGV[0].nil? ? __dir__ : ARGV[0]
これも引数によって値が変わるので変数です。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +MARGIN = 3
これは定数で大丈夫です。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +  if (index % ROW_COUNT).zero? || index.zero?
`|| index.zero?` の部分ですが、 0を何で割っても余りはゼロなので不要だと思います。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +    current_column += 1 if index.positive?
だいぶ細かいですが、`if index.positive?` だと マイナスの値があるのかも？と思っちゃうので ゼロじゃないときの方が分かりやすいと思います。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +    current_column += 1 if index.positive?
current_columnは単に row_countとindexの計算で出るのでは無いでしょうか？
既存の変数を計算すれば算出できる値であれば変数を増やさない方が読みやすくなりますね。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +  ordered_file_list[current_column].append(file_name)
これは修正しなくても大丈夫で、参考までですが、配列に追加するときは以下のように書くのがruby界隈で良く見る書き方です。

```
ordered_file_list[current_column] << file_name
```

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +  0.upto(ROW_COUNT - 1) do |index|
細かいですが、ここは `ROW_COUNT.times`と同じだと思いますのでシンプルな方が良いと思います。

2023-08-28 15:13 UTC, u1tnk commented on 04.ls/command.rb
> +    first_column = ordered_file_list[0][index]
ここからも columnの数は分かっているのでループで書いて欲しいと思います。

2023-08-29 04:40 UTC, muftahpangestu commented on 04.ls/command.rb
> +COLUMN_SPACING = max_length
引数少ない方が読みやすいかな〜って勝手に思いました。
変数に戻して、引数として渡しました。

2023-08-29 04:41 UTC, muftahpangestu commented on 04.ls/command.rb
> +ROW_COUNT = (file_count / 3.to_f).ceil
いつ変数するか定数するのかまだ完全理解できなかった。

価値が全く変わらない→定数
価値が変わる可能性ある→変数

今は変数にしました。

2023-08-29 04:42 UTC, muftahpangestu commented on 04.ls/command.rb
> +CURRENT_PATH = ARGV[0].nil? ? __dir__ : ARGV[0]
変更しました。

2023-08-29 04:44 UTC, muftahpangestu commented on 04.ls/command.rb
> +  if (index % ROW_COUNT).zero? || index.zero?
こちらの`index.zero?`は、最初のループ（index == 0) で`ordered_file_loop`の配列に新しい配列入れてためのコードです。
でも今は新しロジックでこのコード消しました。

2023-08-29 04:44 UTC, muftahpangestu commented on 04.ls/command.rb
> +    current_column += 1 if index.positive?
変更しました！

2023-08-29 04:44 UTC, muftahpangestu commented on 04.ls/command.rb
> +  ordered_file_list[current_column].append(file_name)
参考にします。ありがとうございます

2023-08-29 04:45 UTC, muftahpangestu commented on 04.ls/command.rb
> +  0.upto(ROW_COUNT - 1) do |index|
参考にしました。

2023-08-29 04:45 UTC, muftahpangestu commented on 04.ls/command.rb
> +    first_column = ordered_file_list[0][index]
変更しました。

2023-08-29 17:19 UTC, u1tnk requested changes

2023-08-29 17:19 UTC, u1tnk commented on 04.ls/command.rb
> +    3.times do |column_index|
この3は定数にしたいですね。

2023-08-30 01:35 UTC, muftahpangestu commented on 04.ls/command.rb
> +    3.times do |column_index|
直しました！

2023-08-30 16:26 UTC, u1tnk approved these changes
一つ指摘してますがもう指定の名前にするだけなので approveします！ 変更したらマージしてください。

2023-08-30 16:26 UTC, u1tnk commented on 04.ls/command.rb
> +COLUMN_NUMBER = 3
細かいんですが、 row_countという変数があるので COLUMN_COUNTにそろえたいですね。

2023-08-30 23:43 UTC, merged