adding show hidden files feature
muftahpangestu/ruby-practices pull request #9
Opened 2023-08-31 06:17 UTC by muftahpangestu

2023-09-06 15:35 UTC, u1tnk requested changes

2023-09-06 15:35 UTC, u1tnk commented on 04.ls/command.rb
> +OPTION_COMMANDS = ['-a','-r','-l']
最終的にこうなりますが、 このプラクティスでは aオプションのみにしましょう。

2023-09-06 15:35 UTC, u1tnk commented on 04.ls/command.rb
> +show_hidden_files = true if ARGV.include? '-a'
rubyには標準で オプション(-a/--allなど)を処理してくれるライブラリがあるのでそちらを使うようにしましょう。

2023-09-07 06:59 UTC, muftahpangestu commented on 04.ls/command.rb
> +OPTION_COMMANDS = ['-a','-r','-l']
aオプションのみにしました

2023-09-07 11:24 UTC, u1tnk requested changes

2023-09-07 11:24 UTC, u1tnk commented on 04.ls/command.rb
> +options = ARGV.getopts('a','all')
プラクティスではロングオプション(--all の対応)は必須では無いですが、https://docs.ruby-lang.org/ja/latest/library/optparse.html の「ロングオプション」にあるような方法で書くと便利ですね。
現状でも問題ないです。

2023-09-07 11:24 UTC, u1tnk commented on 04.ls/command.rb
> +show_hidden_files = options['a'] || options['all']
分かりやすい名前を付けているのは良いですね 👍

2023-09-07 11:24 UTC, u1tnk commented on 04.ls/command.rb
> +current_path = ARGV[0].nil? || ARGV[-1] == '-a' ? __dir__ : ARGV[-1]
ここで `-a`を見る必要はもう無いと思います。単純に一番目の引数をパスとしてもらえば良いですね。

2023-09-08 02:40 UTC, muftahpangestu commented on 04.ls/command.rb
> +show_hidden_files = options['a'] || options['all']
変更しました。

2023-09-08 02:41 UTC, muftahpangestu commented on 04.ls/command.rb
> +current_path = ARGV[0].nil? || ARGV[-1] == '-a' ? __dir__ : ARGV[-1]
変更しました。

2023-09-08 14:57 UTC, u1tnk approved these changes

2023-09-20 01:11 UTC, merged